import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                "headline-md": ["Inter"],
                "display-lg": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-lg": ["Inter"],
                "body-lg": ["Inter"],
            },
            colors: {
              "on-secondary-fixed": "#131b2e",
              "on-error": "#ffffff",
              "surface-container": "#e5eeff",
              "secondary-fixed": "#dae2fd",
              "on-surface": "#0b1c30",
              outline: "#737686",
              "surface-bright": "#f8f9ff",
              "on-primary": "#ffffff",
              secondary: "#565e74",
              background: "#f8f9ff",
              "surface-variant": "#d3e4fe",
              "secondary-container": "#dae2fd",
              "on-tertiary-fixed": "#191c1e",
              "tertiary-container": "#6b6e70",
              "on-secondary": "#ffffff",
              "surface-container-high": "#dce9ff",
              "inverse-on-surface": "#eaf1ff",
              "inverse-surface": "#213145",
              "primary-container": "#2563eb",
              surface: "#f8f9ff",
              "on-surface-variant": "#434655",
              "tertiary-fixed-dim": "#c4c7c9",
              "outline-variant": "#c3c6d7",
              "on-tertiary-fixed-variant": "#444749",
              "surface-dim": "#cbdbf5",
              tertiary: "#525657",
              "on-tertiary-container": "#eff1f3",
              primary: "#004ac6",
              "inverse-primary": "#b4c5ff",
              "surface-container-lowest": "#ffffff",
              "surface-container-low": "#eff4ff",
              "on-primary-fixed-variant": "#003ea8",
              "on-error-container": "#93000a",
              "on-primary-container": "#eeefff",
              "error-container": "#ffdad6",
              "on-secondary-container": "#5c647a",
              error: "#ba1a1a",
              "on-secondary-fixed-variant": "#3f465c",
              "on-background": "#0b1c30",
              "surface-container-highest": "#d3e4fe",
              "primary-fixed": "#dbe1ff",
              "secondary-fixed-dim": "#bec6e0",
              "on-tertiary": "#ffffff",
              "surface-tint": "#0053db",
              "tertiary-fixed": "#e0e3e5",
              "primary-fixed-dim": "#b4c5ff",
              "on-primary-fixed": "#00174b",
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px",
            },
            spacing: {
              base: "4px",
              sm: "16px",
              "container-max": "1280px",
              xs: "8px",
              xl: "48px",
              md: "24px",
              lg: "32px",
              
              // DESIGN.md spacing guidelines
              "margin-mobile": "1.25rem",
              "margin-desktop": "2.5rem",
              "gutter": "1rem",
              "stack-sm": "0.5rem",
              "stack-md": "1rem",
              "stack-lg": "2rem",
            },
            fontSize: {
              "headline-md": [
                "24px",
                { lineHeight: "32px", fontWeight: "600" },
              ],
              "display-lg": [
                "48px",
                {
                  lineHeight: "56px",
                  letterSpacing: "-0.02em",
                  fontWeight: "700",
                },
              ],
              "headline-lg-mobile": [
                "24px",
                { lineHeight: "32px", fontWeight: "600" },
              ],
              "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
              "label-md": [
                "14px",
                {
                  lineHeight: "20px",
                  letterSpacing: "0.01em",
                  fontWeight: "500",
                },
              ],
              "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
              "headline-lg": [
                "32px",
                {
                  lineHeight: "40px",
                  letterSpacing: "-0.01em",
                  fontWeight: "600",
                },
              ],
              "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
            },
        },
    },

    plugins: [forms],
};
