import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                "headline-md": ["Inter"],
                "display-lg": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-lg": ["Inter"],
                "body-lg": ["Inter"],
            },
            colors: {
              "on-secondary-fixed": "var(--color-on-secondary-fixed)",
              "on-error": "var(--color-on-error)",
              "surface-container": "var(--color-surface-container)",
              "secondary-fixed": "var(--color-secondary-fixed)",
              "on-surface": "var(--color-on-surface)",
              outline: "var(--color-outline)",
              "surface-bright": "var(--color-surface-bright)",
              "on-primary": "var(--color-on-primary)",
              secondary: "var(--color-secondary)",
              background: "var(--color-background)",
              "surface-variant": "var(--color-surface-variant)",
              "secondary-container": "var(--color-secondary-container)",
              "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
              "tertiary-container": "var(--color-tertiary-container)",
              "on-secondary": "var(--color-on-secondary)",
              "surface-container-high": "var(--color-surface-container-high)",
              "inverse-on-surface": "var(--color-inverse-on-surface)",
              "inverse-surface": "var(--color-inverse-surface)",
              "primary-container": "var(--color-primary-container)",
              surface: "var(--color-surface)",
              "on-surface-variant": "var(--color-on-surface-variant)",
              "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
              "outline-variant": "var(--color-outline-variant)",
              "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
              "surface-dim": "var(--color-surface-dim)",
              tertiary: "var(--color-tertiary)",
              "on-tertiary-container": "var(--color-on-tertiary-container)",
              primary: "var(--color-primary)",
              "inverse-primary": "var(--color-inverse-primary)",
              "surface-container-lowest": "var(--color-surface-container-lowest)",
              "surface-container-low": "var(--color-surface-container-low)",
              "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
              "on-error-container": "var(--color-on-error-container)",
              "on-primary-container": "var(--color-on-primary-container)",
              "error-container": "var(--color-error-container)",
              "on-secondary-container": "var(--color-on-secondary-container)",
              error: "var(--color-error)",
              "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
              "on-background": "var(--color-on-background)",
              "surface-container-highest": "var(--color-surface-container-highest)",
              "primary-fixed": "var(--color-primary-fixed)",
              "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
              "on-tertiary": "var(--color-on-tertiary)",
              "surface-tint": "var(--color-surface-tint)",
              "tertiary-fixed": "var(--color-tertiary-fixed)",
              "primary-fixed-dim": "var(--color-primary-fixed-dim)",
              "on-primary-fixed": "var(--color-on-primary-fixed)",
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px",
            },
            spacing: {
              base: "4px",
              sm: "16px",
              "container-max": "1280px",
              xs: "8px",
              xl: "48px",
              md: "24px",
              lg: "32px",
              
              // DESIGN.md spacing guidelines
              "margin-mobile": "1.25rem",
              "margin-desktop": "2.5rem",
              "gutter": "1rem",
              "stack-sm": "0.5rem",
              "stack-md": "1rem",
              "stack-lg": "2rem",
            },
            fontSize: {
              "headline-md": [
                "24px",
                { lineHeight: "32px", fontWeight: "600" },
              ],
              "display-lg": [
                "48px",
                {
                  lineHeight: "56px",
                  letterSpacing: "-0.02em",
                  fontWeight: "700",
                },
              ],
              "headline-lg-mobile": [
                "24px",
                { lineHeight: "32px", fontWeight: "600" },
              ],
              "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
              "label-md": [
                "14px",
                {
                  lineHeight: "20px",
                  letterSpacing: "0.01em",
                  fontWeight: "500",
                },
              ],
              "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
              "headline-lg": [
                "32px",
                {
                  lineHeight: "40px",
                  letterSpacing: "-0.01em",
                  fontWeight: "600",
                },
              ],
              "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
            },
        },
    },

    plugins: [forms],
};
